### ISSUE TITLE
Using Raylib.lean under windows

### ISSUE THREAD

**Issue by Wasabi2007** [KislyjKisel/Raylib.lean#3]
Hello there. This might be just a general knowledge gab.
But how do I need to setup my enviroment to use your lean bindings under windows?
I tried to set the `cc` to MSVCs `cl.exe` and MSYS2s 'gcc.exe' or `clang.exe` and nether running from a MSYS2 console or Powershell console resulted an an success full compiliation of the ` raylib-test`

Closest I got was running lake in raylibs prefered mingw enviorment https://github.com/skeeto/w64devkit/ with `cc` set to `gcc.exe`
but still got compile errors like these for parts of the compilation:
```
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive
error: stderr:
ld.lld: error: undefined symbol: UnloadImage
>>> referenced by raylib-lean.a(structures.o):(lean_raylib_Image_finalize)
>>> referenced by raylib-lean.a(functions.o):(lean_raylib__GenTextureMipmaps)
[...]
```
I assume it has problems linking because gcc binaries and leanc are not compatible. But with clang the default setup has again trouble finding the proper standart libary headers.

I appreaceate any help.
Grettings from Wasabi

**Comment by KislyjKisel** [comment]
Try adding `moreLinkArgs := #[s!"-L{__dir__}/raylib/build/raylib", "-lraylib"]` to the package config in the lakefile.

**Comment by Wasabi2007** [comment]
This only causes the build process try to link against it self during dll creation
```
info: [21/58] Linking raylib-lean.dll
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive -L.\.lake/packages\raylib/raylib/build/raylib -lraylib
```

**Comment by KislyjKisel** [comment]
I don't understand you. `raylib-lean` is the C bindings library, while `raylib` is raylib itself.

I haven't managed to build `Raylib.lean` under windows yet, but at least moving "-lraylib" from exe link args to package link args removed "undefined reference"s to raylib functions (for me remaining visible errors are about stdlibs linkage and IIUC caused by incorrect compiler setup rather than `Raylib.lean` configuration).

I'll try gcc/different env and `extern_lib raylib := inputFile "..."` next.

**Comment by Wasabi2007** [comment]
I am currently trying to build the test exetuable `raylib-test` executable.
For now I reduced my case to just building the `raylib` target.

my process is currently this:
- I set `cc` to `gcc` in my main lean file for `require raylib from git`
- I open the `w64devkit` enviroment from https://github.com/skeeto/w64devkit/ and navigate into my lean project folder
- I call `lake update`
- I call `lake run raylib/buildSubmodule`
- I call `lake build raylib`

After those steps I get the first mentioned linker errors.
```
[17/74] Linking raylib-lean.dll
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive
error: stderr:
ld.lld: error: undefined symbol: UnloadImage
>>> referenced by raylib-lean.a(structures.o):(lean_raylib_Image_finalize)
>>> referenced by raylib-lean.a(functions.o):(lean_raylib__GenTextureMipmaps)

ld.lld: error: undefined symbol: rlGetTextureIdDefault
>>> referenced by raylib-lean.a(structures.o):(lean_raylib_Texture_finalize)
>>> referenced by raylib-lean.a(structures.o):(lean_raylib__Texture_getDefault)
```

After your message I tried to add `moreLinkArgs := #[s!"-L{__dir__}/raylib/build/raylib", "-lraylib"]` to 
```
package raylib {
  srcDir := "src/lean"
  packagesDir := packagesDir
  moreLeanArgs := #["-DautoImplicit=false"] ++
    if (get_config? libffi).isSome
      then #[s!"--load-dynlib=./{packagesDir}/libffi/lib/libffi.so"] -- why not automatic?
      else #[]
  moreServerArgs := #["-DautoImplicit=false"]
}
```
leading the linker to complain about it not finding any `raylib` to link into `raylib.dll`.
Sorry I apparently did not copy the full error message into my last post.

```
info: [21/58] Linking raylib-lean.dll
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive -L.\.lake/packages\raylib/raylib/build/raylib -lraylib
error: stderr:
lld: error: unable to find library -lraylib
```

I assume I missunderstood where you wanted me to add the linker flags?

**Comment by KislyjKisel** [comment]
No, you understood me correctly. What files are there in `.lake/packages\raylib/raylib/build/raylib`? For me there is a `libraylib.a` file which the linker finds. Maybe there is an issue with incorrect library naming.

**Comment by Wasabi2007** [comment]
I have a bunch of project files in there. No build executables by the look of things.
![grafik](https://github.com/KislyjKisel/Raylib.lean/assets/2978690/0f8d893c-8290-41e5-b804-b293b8eec2b1)

**Comment by KislyjKisel** [comment]
Did `lake run raylib/buildSubmodule` succeed?

**Comment by Wasabi2007** [comment]
OK I have some Progress after adding 
`"-G Unix Makefiles"` to `cmakeBuildArgs` I have a `libraylib.a`

Yes `lake run raylib/buildSubmodule` did seem to succeed I even had a proppersized debug `libraylib.lib`

But I think I stick to "Unix Makefiles" that seems to produce results closer to what we want for now.

**Comment by Wasabi2007** [comment]
I also get a different linker error I see If I might just need to add the other libaries for linking
```
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive -L.\.lake/packages\raylib/raylib/build/raylib -lraylib
error: stderr:
ld.lld: error: undefined symbol: __declspec(dllimport) CreateDIBSection
>>> referenced by G:/Private_Projects/LeanStuff/raylibTest/.lake/packages/raylib/raylib/src/external/glfw/src/win32_window.c:124
>>>               libraylib.a(win32_window.c.obj):(createIcon)
```

**Comment by KislyjKisel** [comment]
You need to link with `-lgdi32`. `-lwinmm` and `-lopengl32` are mentioned [here](https://github.com/raysan5/raylib/wiki/Working-on-Windows#a-note-on-dependencies) too.

**Comment by Wasabi2007** [comment]
Getting closer just 3 Linker errors left.
Just have to figure out what link target are missing.
```
error: > c:\Users\UserName\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe -shared -o .\.lake/packages\raylib\.lake\build\lib\raylib-lean.dll -Wl,--whole-archive .\.lake/packages\raylib\.lake\build\lib\raylib-lean.a -Wl,--no-whole-archive -L.\.lake/packages\raylib/raylib/build/raylib -lraylib -L.\.lake/packages\raylib/raylib/build/raylib/external/glfw/src -LC:/Windows/System32 -lglfw3 -lgdi32 -lwinmm -lopengl32
error: stderr:
ld.lld: error: undefined symbol: _amsg_exit
>>> referenced by C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:94
>>>               c:\Users\Jerry\.elan\toolchains\leanprover--lean4---stable/lib/dllcrt2.o:(_CRT_INIT)
>>> referenced by C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:126
>>>               c:\Users\Jerry\.elan\toolchains\leanprover--lean4---stable/lib/dllcrt2.o:(_CRT_INIT)
>>> referenced by C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:126
>>>               c:\Users\Jerry\.elan\toolchains\leanprover--lean4---stable/lib/dllcrt2.o:(__DllMainCRTStartup)
>>> referenced 1 more times

ld.lld: error: undefined symbol: vfprintf
>>> referenced by C:/M/B/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:151
>>>               libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):(__report_error)

ld.lld: error: undefined symbol: fprintf
>>> referenced by libclang_rt.builtins-x86_64.a(emutls.c.obj):(emutls_init)
>>> referenced by libclang_rt.builtins-x86_64.a(emutls.c.obj):(win_error)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: external command `c:\Users\Jerry\.elan\toolchains\leanprover--lean4---stable\bin\leanc.exe` exited with code 1
```

**Comment by KislyjKisel** [comment]
Try adding `-lmsvcrt`.

**Comment by Wasabi2007** [comment]
I could successfuly build the raylib package with those Linker additions :D 
`  moreLinkArgs := #[s!"-L{__dir__}/raylib/build/raylib", "-lraylib", s!"-L{__dir__}/raylib/build/raylib/external/glfw/src", "-LC:/Windows/System32","-lglfw3", "-lgdi32", "-lwinmm", "-lopengl32" , "-lmsvcrt"]
`

**Comment by KislyjKisel** [comment]
What about an executable?

**Comment by Wasabi2007** [comment]
the executable is still missing some system dlls

```
error: stderr:
ld.lld: error: undefined symbol: chmod
>>> referenced by libleanrt.a(io.cpp.obj):(lean_chmod)

ld.lld: error: undefined symbol: open
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_prim_handle_mk)

ld.lld: error: undefined symbol: fdopen
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_prim_handle_mk)
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_prim_handle_mk)
>>> referenced by libleanrt.a(process.cpp.obj):(lean::setup_stdio(_SECURITY_ATTRIBUTES*, void**, lean_object**, bool, lean::stdio))

ld.lld: error: undefined symbol: mkdir
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_create_dir)

ld.lld: error: undefined symbol: rmdir
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_remove_dir)

ld.lld: error: undefined symbol: getcwd
>>> referenced by libleanrt.a(io.cpp.obj):(lean_io_current_dir)

ld.lld: error: undefined symbol: snprintf
>>> referenced by libc++.a(string.cpp.obj):(std::__1::to_string(float))
>>> referenced by libc++.a(string.cpp.obj):(std::__1::to_string(double))
>>> referenced by libc++.a(string.cpp.obj):(std::__1::to_string(long double))
>>> referenced 7 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by KislyjKisel** [comment]
Try adding `-lmingw32`. There are also `-lmingwex`, `-ladvapi32`, `-lshell32`, `-luser32`, `-lkernel32` (don't know what they do, but they should be linked by default. [src](https://stackoverflow.com/q/76675060)).

**Comment by Wasabi2007** [comment]
Your source looked promising but no luck with those ones.

**Comment by KislyjKisel** [comment]
When you tried clang, did you try the one packaged with Lean or the one in MSYS2?

**Comment by Wasabi2007** [comment]
I Have it
![grafik](https://github.com/KislyjKisel/Raylib.lean/assets/2978690/4a50258c-26b6-4130-81f6-961a5d133653)

You can not use the default `msvcrt` and so on. You first have to add the lean instalation folder as Link source

To recab, my final set up is now:
```
package raylib {
  srcDir := "src/lean"
  packagesDir := packagesDir
  moreLinkArgs := #[
    "-LC:/Users/UserName/.elan/toolchains/leanprover--lean4---stable/lib"
    ,s!"-L{__dir__}/raylib/build/raylib"
    , "-lraylib"
    , s!"-L{__dir__}/raylib/build/raylib/external/glfw/src"
    , "-LC:/Windows/System32"
    ,"-lglfw3"
    , "-lgdi32"
    , "-lwinmm"
    , "-lopengl32"
    , "-lmsvcrt"]
  moreLeanArgs := #["-DautoImplicit=false"] ++
    if (get_config? libffi).isSome
      then #[s!"--load-dynlib=./{packagesDir}/libffi/lib/libffi.so"] -- why not automatic?
      else #[]
  moreServerArgs := #["-DautoImplicit=false"]
}
```
I'll asume there is a nicer way to get that folder then pasting in the full instalation path to lean ^^

None of the default libs like `mingw32` needed to be added anywhere.

and finaly forcing cmake to generate unix make files:
```
  let mut cmakeBuildArgs : Array String := #[
    "-DCUSTOMIZE_BUILD=ON",
    "-DWITH_PIC=ON",
    "-DBUILD_EXAMPLES=OFF",
    "-G Unix Makefiles"
  ]
```

In addition setting `cc` to `gcc` and using the mingw32 enviroment https://github.com/skeeto/w64devkit/

I hope this helps wich ever poor soul runs into the same or similar issues.

Thank you for all your help. :D

**Comment by KislyjKisel** [comment]
Congratulations! :)

> I'll asume there is a nicer way to get that folder then pasting in the full instalation path to lean ^^

There is a function `Lake.getLeanSystemLibDir` which returns the required path (it requires `Lake.MonadLakeEnv` though, idk if it can be used in package configuration).
