### ISSUE TITLE
Example of specifying options

### ISSUE THREAD

**Issue by Quoteme** [KislyjKisel/Raylib.lean#4]
Hi! Thanks a lot for your great work. I am currently facing some problems while trying to use my systems raylib library.

In your readme, [it states](https://github.com/KislyjKisel/Raylib.lean#options), that I should specify the `raylib` option as `"system"` in the require statement of my lakefile. I currently have the following:

```lean
import Lake
open Lake DSL

package «mathcraft» where
  -- add package configuration options here

  leanOptions := #[
    ⟨`pp.unicode.fun, true⟩, -- pretty-prints `fun a ↦ b`
    ⟨`pp.proofs.withType, false⟩
  ]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.4.0"

require raylib from git
  "https://github.com/KislyjKisel/Raylib.lean" @ "c62c750"
  with NameMap.empty
    |> (.insert . `raylib "system")
    |> (.insert . `wayland "ON")

lean_lib «Mathcraft» where
  -- add library configuration options here

@[default_target]
lean_exe «mathcraft» where
  root := `Main
  moreLinkArgs := #["-Llake-packages/raylib/raylib/build/raylib", "-lraylib"]
  ```
  
  However, this does not seem to use my system's raylib. Am I doing something wrong here? I would very much appreciate it if you could provide an example of how to specify these settings! Thanks a lot!

**Comment by KislyjKisel** [comment]
`"-Llake-packages/raylib/raylib/build/raylib"` in `moreLinkArgs` in `lean_exe` is for using the built submodule. It can be `-L/usr/local/lib` for manually installed raylib, and probably isn't required if raylib was installed using the system's package manager.

It seems like without submodules present the bindings won't compile because they need raygui headers. Also it tries to compile "\n" files. I'll look into it.

**Comment by KislyjKisel** [comment]
You can try with the [toolchain-4.4.0](https://github.com/KislyjKisel/Raylib.lean/tree/toolchain-4.4.0) branch (commit `8b21ddf`). Make sure you used `lake` with `-R` after adding `with` options to the `lakefile`.

**Comment by KislyjKisel** [comment]
Note that `wayland` flag is for customizing submodule build, it won't have any effect on the system's raylib.

**Comment by Quoteme** [comment]
Thanks a lot! Your changes in [toolchain-4.4.0](https://github.com/KislyjKisel/Raylib.lean/tree/toolchain-4.4.0) allowed me to compile my project!
